Repository AmGthrow/CMSC128C, pull requests merged in 2022-03, with the labels that each got.

#11 Added API endpoint for clients joining the email waitlist
  .gitignore
  server/.gitignore
  server/README.md
  server/docs/waitlistAPI.gif
  server/package-lock.json
  server/package.json
  server/server.js
  server/spreadsheet.js
  server/src/index.html
Labels: enhancement

#12 Codercademy Hero shot
  client/src/webpages/Home.js
  client/src/webpages/hero-bg.jpg
  client/src/webpages/landingPage.css
  client/src/webpages/logo_textless.png
Labels: bug, enhancement, help wanted

#36 List repeating data
  client/src/domain/MainFeatures/MainFeatures.js
Labels: enhancement

#44 Class list Page
  client/src/App.css
  client/src/App.js
  client/src/components/ClassCard/ClassCard.js
  client/src/components/ClassCard/ClassCard.module.css
  client/src/domain/ClassList/ClassList.js
  client/src/domain/ClassList/ClassList.module.css
  client/src/webpages/ClassListPage.js
Labels: bug, help wanted

#50 Svr file structure
  server/.gitignore
  server/controller/description,txt
  server/controller/waitlist.js
  server/database/description.txt
  server/database/spreadsheet.js
  server/middleware/description.txt
  server/middleware/swaggerDocs.middleware.js
  server/model/description.txt
  server/package-lock.json
  server/package.json
  server/route/description,txt
  server/route/router.js
  server/server.js
Labels: documentation, enhancement
